name: Dependabot Auto Approve & Merge (VULNERABLE)

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch metadata
        id: meta
        uses: dependabot/fetch-metadata@v1

      - name: Log metadata
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Update type: ${{ steps.meta.outputs.update-type }}"
          echo "Dependency type: ${{ steps.meta.outputs.dependency-type }}"

      - name: Auto-approve and merge
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --squash --auto "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
